# Generated by Django 5.1 on 2024-08-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_doctor_department_specialities_department"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialities",
            name="department",
        ),
        migrations.AddField(
            model_name="specialities",
            name="department",
            field=models.ManyToManyField(
                null=True, related_name="specialities", to="hospital.department"
            ),
        ),
    ]
