# Generated by Django 5.1 on 2024-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_alter_specialities_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
