# Generated by Django 5.1 on 2024-08-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_doctor_status"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialities",
            name="department",
        ),
        migrations.AddField(
            model_name="specialities",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialities",
                to="hospital.department",
            ),
        ),
    ]
