# Generated by Django 5.1 on 2024-08-22 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_remove_specialities_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialities",
            name="bunk_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
