# Generated by Django 5.1 on 2024-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="pharmacy",
        ),
    ]
