# Generated by Django 5.1 on 2024-08-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_patient_pharmacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="staff",
        ),
        migrations.AddField(
            model_name="room",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="number",
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="patient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
    ]
