# Generated by Django 5.1 on 2024-08-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_specialities_bunk_cost"),
        ("patients", "0003_remove_room_staff_room_doctor_room_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="doctor.doctor",
            ),
        ),
    ]
