# Generated by Django 5.1 on 2024-08-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointment_patient"),
        ("patients", "0002_remove_patient_pharmacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
    ]
