# Generated by Django 5.1 on 2024-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_appointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="service_description",
            field=models.TextField(
                default="Invoice Description\nProject Name: [Your Project Name]\nClient: [Client Name]\nDate: [Invoice Date]\nInvoice Number: [Invoice Number]"
            ),
        ),
    ]
