# Generated by Django 5.1 on 2024-08-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_alter_appointment_doctor"),
        ("doctor", "0005_doctor_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctor.doctor",
            ),
        ),
    ]
