# Generated by Django 5.1 on 2024-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_alter_prescription_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="bunk",
            field=models.BooleanField(default=False),
        ),
    ]
